image: Visual Studio 2017
configuration: Release
platform: Any CPU
before_build:
- cmd: nuget restore
build:
  verbosity: minimal
after_test:
- cmd: dotnet pack --output $(APPVEYOR_BUILD_FOLDER)
artifacts:
  - path: '*.nupkg'